use_frameworks!

platform :ios, '8.0'

target 'MockAPIData-iOS-SDK_Example' do
  pod 'MockAPIData-iOS-SDK', :path => '../'

  pod 'AFNetworking'
  target 'MockAPIData-iOS-SDK_Tests' do
    inherit! :search_paths

  end
end
